# Тикер базового актива (например, RTS, если нужен фьючерс на индекс РТС)
ticker: 'RTS'

# Провайдер или метка (группа папок для хранения данных, настраивайте произвольно)
provider: 'moex'

# Дата старта выгрузки минутных данных (YYYY-MM-DD)
start_date_download_minutes: '2014-01-01'

# Директория для итоговых файлов (относительно этого скрипта или полный путь)
output_dir: 'C:/Users/Alkor/gd/data_quote_db'

# Время для формирования дневной свечи (формат ЧЧ:ММ:СС)
time_start: "21:00:00"
time_end: "20:59:59"

# Файл БД с дневными котировками
path_db_day: 'C:/Users/Alkor/gd/data_quote_db/{ticker}_days.sqlite'

# path_db_minute может быть:
# - точный путь к файлу,
# - путь с шаблоном (например "C:/.../minutes_RTS_*.sqlite"),
# - путь к каталогу, из которого будут взяты файлы minutes_{ticker}_*.sqlite
path_db_minute: 'C:/Users/Alkor/gd/data_quote_db'  # папка с БД минутных котировок по годам

# "from_settings" или "from_db"
#download_mode: "from_settings"  # загрузка с даты указанной в settings
download_mode: "from_db"  # загрузка в БД, если файлы уже есть там с последней даты в БД