# Тикер базового актива (например, RTS, если нужен фьючерс на индекс РТС)
ticker: 'RTS'

# Провайдер или метка (группа папок для хранения данных, настраивайте произвольно)
provider: 'moex'

# Дата старта выгрузки минутных данных (YYYY-MM-DD)
start_date_download_minutes: '2014-01-01'

# Директория для итоговых файлов (относительно этого скрипта или полный путь)
output_dir: 'C:/Users/Alkor/gd/data_quote_db'

time_start: "21:00:00"
time_end: "20:59:59"
path_db_day: 'C:/Users/Alkor/gd/data_quote_db'
path_db_minute: 'C:/Users/Alkor/gd/data_quote_db'  # папка с годовыми БД
